employees/urls.py
from django.urls import path

from .import views

urlpatterns=[
    path('emplooyes',views.login),
    path('home',views.home),
]

jadm/urls.py
from django.urls import path

app_name='jadmin'
from . import views
urlpatterns=[
    path('home',views.homes,name="homes"),
    path('login',views.loges,name="loges"),

]

jobportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobseekers.urls')),
    path('employees/',include('employees.urls')),
    path('jadmin/',include('jadm.urls')),
]

jobseekers/urls.py
from django.urls import path

from . import views
app_name='jseeker'
urlpatterns=[
    path('',views.login,name='log',),
    path('jobsearch',views.search,name='search'),
    path('jobdeatails',views.deatail,name='details'),
]

employees/models.py
from django.db import models

# Create your models here.

jadm/models.py
from django.db import models

# Create your models here.

jobseekers/models.py
from django.db import models

# Create your models here.

employees/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request,'emplooyes/login.html')

def home(request):
    return render(request,'home/home.html')

jadm/views.py
from django.shortcuts import render

# Create your views here.

def homes(request):
    return render(request,'jadm/home.html')

def loges(request):
    return render(request,'jadm/login.html')

jobseekers/views.py
from django.shortcuts import render

# Create your views here.

def login(request):
    return render(request,'jobseekers/login.html')

def search(request):
    return render(request,'jobseekers/jobsearch.html')

def deatail(request):
    return render(request,'jobseekers/jobdeatails.html')

employees/templates/employees/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    home
</body>
</html>

employees/templates/employees/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    log
</body>
</html>

jadm/templates/jadm/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'jadmin:loges' %}">names</a>
    <img src="{% static 'image/images.jpg' %}" alt="">
</body>
</html>

jadm/templates/jadm/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'jadmin:loges' %}">homes
    </a>
    <img src="{% static 'image/down.jpg' %}" alt="">
</body>
</html>

jobseekers/templates/jobseekers/jobdeatails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    hello
</body>
</html>

jobseekers/templates/jobseekers/jobsearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=lo, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    log
</body>
</html>

jobseekers/templates/jobseekers/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
     <a href="{% url 'jseeker:details' %}">jobdetails</a>
    <img src="{% static 'images/download.jpg' %}" alt="" height="500px">
</body>
</html>